package templates

import (
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/std/math/cmp"
	"gnark_server/primitives"
)

// AuctionSettleCircuitConfig holds compile-time parameters.
type AuctionSettleCircuitConfig struct {
	TmRange frontend.Variable // upper bound for range checks
}

// AuctionSettleCircuit proves that the auctioneer has correctly settled an
// auction by:
//
//  1. Revealing the preimage of the winning bid's commitB (USDC payout for Bob).
//     This proves the auctioneer correctly decrypted the winning bid — only
//     the holder of sk_auction can obtain saltB via ML-KEM.Decapsulate.
//
//  2. Creating a valid NFT commitment for Alice (the auction winner).
//     The auctioneer generates a fresh saltAlice and builds the new commitment
//     using Alice's spend public key (recovered from the decrypted bid message).
//
//  3. Binding the settled NFT tokenId to what was locked at auction init.
//     The contract verifies stNftTokenId against the locked commitment on-chain.
//
//  4. Publishing stWinningAmount as a public output so losing bidders can use
//     it as the threshold in their AuctionNotWinning proofs. The circuit
//     constrains that stWinningAmount equals the amount inside commitB.
//
// The contract releases stCommitB to be spendable by Bob, inserts
// stCommitWinnerNft as Alice's new NFT note, and records stWinningAmount so
// losing bidders can prove their bid was strictly less than it.
//
// Public statement (5 elements):
//
//	[stAuctionId, stCommitB, stCommitWinnerNft, stNftTokenId, stWinningAmount]
type AuctionSettleCircuit struct {
	Config AuctionSettleCircuitConfig

	// --- public inputs ---
	StAuctionId       frontend.Variable `gnark:",public"` // identifies the auction being settled
	StCommitB         frontend.Variable `gnark:",public"` // winning bid's USDC payout destination (Bob)
	StCommitWinnerNft frontend.Variable `gnark:",public"` // new NFT commitment for Alice (winner)
	StNftTokenId      frontend.Variable `gnark:",public"` // NFT token ID — contract checks vs locked commitment
	StWinningAmount   frontend.Variable `gnark:",public"` // winning bid amount — threshold for not-winning proofs

	// --- private witnesses: winning bid data (from auctioneer's ML-KEM decryption) ---
	WtPkBob       frontend.Variable // Bob's spend public key (from decrypted bid message)
	WtSaltB       frontend.Variable // HKDF(ss, "note salt") — Bob's USDC note salt
	WtBidAmount   frontend.Variable // winning bid amount (constrained == StWinningAmount)
	WtUsdcTokenId frontend.Variable // USDC token ID

	// --- private witnesses: NFT transfer to winner ---
	WtPkAlice    frontend.Variable // Alice's spend public key (from decrypted bid message)
	WtSaltAlice  frontend.Variable // fresh random salt for Alice's new NFT note
	WtNftTokenId frontend.Variable // NFT token ID (constrained == StNftTokenId)
}

func (circuit *AuctionSettleCircuit) Define(api frontend.API) error {
	// 1. Verify commitB preimage — proves the auctioneer correctly decrypted
	// the winning bid. Only the holder of sk_auction can recover saltB.
	commitB := primitives.Erc20CommitmentV2(api,
		circuit.WtPkBob,
		circuit.WtSaltB,
		circuit.WtBidAmount,
		circuit.WtUsdcTokenId,
	)
	api.AssertIsEqual(commitB, circuit.StCommitB)

	// 2. Build Alice's new NFT commitment using her spend public key and a fresh
	// salt generated by the auctioneer. The auctioneer knows pk_A from the
	// decrypted bid message field id_B (which includes pk_A^spend).
	commitWinnerNft := primitives.Erc721Commitment(api,
		circuit.WtNftTokenId,
		circuit.WtPkAlice,
		circuit.WtSaltAlice,
	)
	api.AssertIsEqual(commitWinnerNft, circuit.StCommitWinnerNft)

	// 3. NFT tokenId consistency — private witness must match the public value
	// that the contract cross-checks against the locked commitment.
	api.AssertIsEqual(circuit.WtNftTokenId, circuit.StNftTokenId)

	// 4. Winning amount consistency — the private amount used to build commitB
	// must equal the public StWinningAmount so losing bidders have a verifiable
	// threshold to compare against in their AuctionNotWinning proofs.
	api.AssertIsEqual(circuit.WtBidAmount, circuit.StWinningAmount)

	// 5. Range check on bid amount — prevents zero or overflowing values.
	isPositive := cmp.IsLess(api, 0, circuit.WtBidAmount)
	api.AssertIsEqual(isPositive, 1)

	isInRange := cmp.IsLess(api, circuit.WtBidAmount, circuit.Config.TmRange)
	api.AssertIsEqual(isInRange, 1)

	return nil
}
