---
config:
  look: handDrawn
  theme: redux
---

sequenceDiagram
    participant alice as Alice
    participant chain as Blockchain
    participant bob as Bob
    participant auctioneer as Auctioneer

    note over alice, auctioneer: Initial Setup

    note over alice: has USDC
    note over bob: has an NFT

    note over chain: runs DvP smart contract

    note over alice: has (ML-KEM) view key pair<br>has (hash-based) spend key pair
    note over bob: has (ML-KEM) view key pair<br>has (hash-based) spend key pair
    note right of auctioneer: $$(sk_{auction}, pk_{auction}) \longleftarrow ML{-}KEM. Keygen(\lambda)$$

    note over alice, auctioneer: Ready to transact

    %% Bob puts NFT for sale
    note right of bob: nf $$ = H(sk_{B}, index)$$
    bob ->> chain: $$nf, \pi, C_{B}$$

    %% smart contract locks the commitment
    note over chain: Verify ZKP

    %% flow to check if ZK proof is correct
    alt Spent(nf) == true
        chain ->> bob: error
    else Verify(π) = false 
        chain ->> bob: error
    else Verify(π) = true
        note over chain: mark nullifier as locked
    end

    %% 
    note left of alice: $$ctxt_{1}, ss = ML{-}KEM.Encapsulate(pk_{auction})$$
    
    %% create destination commitment
    note left of alice: $$commit_{B} = commit(pk_{B}^{spend}, salt_{B}, token_{id}, amount)$$

    %% additional tx data
    note left of alice: $$ msg = (id_{B} || pk_{B}^{spend}||token_{id} || amount)$$
    
    %% encrypt additional tx data
    note left of alice: $$ctxt_{2}, err = AEAD.Enc(k, msg)$$

    %% create nullifier
    note left of alice: $$nf = H(sk_{A}^{spend}, index)$$

    %% create zk proof
    note left of alice: π: <br>-I know the (spend) secret key for this nullifier<br> - The nullifier is well-formed

    %% submit bid to chain
    alice ->>chain: $$tx_{id}, ctxt_{1}, commit_{A}, commit_{B}, ctxt_{2}, nf_{A}, \pi_{A}$$

    %% check if nullifier has already been spent
    alt Spent(nf) == true
        chain ->> alice: error
    
    %% check if zk proof is not valid
    else Verify(π) = false 
        chain ->> alice: error
    
    %% check if zk proof is valid
    else Verify(π) = true
        note over chain: mark nullifier as locked
    end
    
    %% notify auctioneer of new bid
    chain -->> auctioneer: new bid
    
    %% obtain shared secret
    note right of auctioneer: $$ss \longleftarrow ML{-}KEM.Decapsulate(ctxt_{1})$$
    
    %% derive symmetric key
    note right of auctioneer: $$k \longleftarrow HKDF(salt_{B}, ss, info_{B}, len)$$

    %% obtain msg
    note right of auctioneer: $$msg, ok \longleftarrow AEAD.Dec(k, ctxt_{2}, ctxt_{1})$$
    
    %% parse msg
    note right of auctioneer: $$(id_{B}, pk_{B}^{spend}, token_{id}, amount) \longleftarrow Parse(msg)$$

    note right of auctioneer: $$C = Commit(pk_{B}^{spend}, salt_{B}, token_{id}, amount) $$

    %% check if obtained commitment matches the submitted commitment
    note right of auctioneer: $$C =^{?} commit_{B}$$

    alt $$C \neq commit_{B}$$
        auctioneer ->> chain: fraud
    
    else $$C {=}{=} commit_{B}$$
        note right of auctioneer: create ZKP
        auctioneer ->> chain: finalize auction
    end



